name: Bug Report
description: File a bug report to help us improve
title: "[Bug] "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report! This will be automatically converted to a Bug Report (BR) document and processed through our Kanban intake workflow.
        
        📖 **Need help?** See our [GitHub Submission Guide](https://github.com/earlution/ai-dev-kit/blob/main/packages/frameworks/kanban/FR_BR_UXR_GITHUB_SUBMISSION_GUIDE.md) for detailed instructions.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: One sentence description of the bug
      placeholder: Brief description of the bug
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the bug
      placeholder: |
        - What is the bug?
        - What should happen vs. what actually happens?
        - When does it occur?
        - Who is affected?
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this bug?
      options:
        - CRITICAL
        - HIGH
        - MEDIUM
        - LOW
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the impact?
      options:
        - CRITICAL
        - HIGH
        - MEDIUM
        - LOW
    validations:
      required: true

  - type: textarea
    id: affected_component
    attributes:
      label: Affected Component
      description: Primary component or area affected
      placeholder: e.g., User Authentication, Payment Processing, UI Component

  - type: checkboxes
    id: affected_areas
    attributes:
      label: Affected Areas
      options:
        - label: Backend/API
        - label: Frontend/UI
        - label: Database/Schema
        - label: Integration/External Service
        - label: Documentation
        - label: Other (specify in description)

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Clear steps to reproduce the bug
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
        4. Expected result
        5. Actual result
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Environment details
      placeholder: |
        Environment: Production/Staging/Development
        Version: Version number or commit hash
        Browser/Platform: [If applicable]
        OS: [If applicable]

  - type: dropdown
    id: user_impact
    attributes:
      label: User Impact
      description: How does this affect users?
      options:
        - Critical - System unusable
        - High - Major functionality broken
        - Medium - Some functionality affected
        - Low - Minor issue, workaround available
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: If a workaround exists, describe it here
      placeholder: Optional workaround description

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information about the bug
      placeholder: Add any other context about the problem here

